CREATE DATABASE aula_pedido;

#USAR BANCO DE DADDOS
USE aula_pedido;

#CRIAR TABELA
CREATE TABLE categoria (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(25) UNIQUE NOT NULL
);

#INSERIR UM DADO NA CATEGORIA
INSERT INTO categoria VALUES
(NULL,"Lanches");


